version: 2
jobs:
  build:
    parallelism: 2
    working_directory: ~/campsited
    docker:
      - image: circleci/ruby:2.3.7-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""

    steps:
      - checkout # special step to check out source code to working directory
      # - run:
      #     name: Install latest version of Chrome
      #     command: |
      #       wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
      #       sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
      #       sudo apt-get -f install -y
      #       sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
      #       sudo rm /usr/local/bin/chromedriver

      - restore_cache:
          keys:
            - campsited-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: campsited-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: cp config/database.yml.sample config/database.yml
      - run: bundle exec rake db:create db:schema:load --trace

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
